<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>SSW.Benchmarks.SerializationProtobuf</AssemblyName>
    <RootNamespace>SSW.Benchmarks.SerializationProtobuf</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="protobuf-net" Version="3.2.56" />
  </ItemGroup>
</Project>
