/** 기존 공개 URL을 새 API 기반 상세 화면으로 연결하기 위한 slug만 보관한다. */
export const LEGACY_LOG_SLUGS = [
  'access-modifiers-are-collaboration-documentation',
  'ambiguous-support-leaves-negative-experiences',
  'ask-ai-for-options-before-implementation',
  'canvas-dodge-game-before-game-development',
  'consider-human-hallucination-before-ai-hallucination',
  'developer-responsibility-does-not-disappear-in-gray-areas',
  'distinguishing-ai-bubble-from-reality-is-your-responsibility',
  'do-not-call-restful-and-rpc-the-same',
  'do-not-trust-ai-evaluations-that-ignore-model-tiers',
  'employment-contract-that-damaged-trust-from-the-start',
  'excel-row-mapping-wpf-app',
  'first-ar-project-using-real-space-and-motion',
  'health-as-the-most-important-long-term-asset',
  'interview-where-i-had-to-prove-my-hobby',
  'license-is-not-something-to-negotiate-after-success',
  'manual-work-is-not-safe-just-because-ai-has-security-risks',
  'mutual-respect-creates-a-virtuous-cycle-of-knowledge',
  'radial-nerve-palsy-and-ai-workflow',
  'recovery-after-alternate-all-nighters',
  'rules-need-both-compliance-and-enforceable-structure',
  'scale-and-appearance-do-not-guarantee-business-integrity',
  'thoughts-on-writing-with-ai',
  'why-i-started-software-development',
  'why-object-oriented-design-and-patterns-should-be-understood-together',
  'why-object-oriented-design-matters-more-in-the-ai-era',
] as const;
