<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsBenchmarkProject>true</IsBenchmarkProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SSW.Benchmarks.SerializationProtobuf\SSW.Benchmarks.SerializationProtobuf.csproj" />
  </ItemGroup>
</Project>
